### ISSUE TITLE
Error: Error during creation of user

### ISSUE THREAD

**Issue by laki9** [opencit/opencit#12]
The following error and exception occurred in the first step of the installation(mtwilson-server-2.0.7-jdk_glassfish_monit.bin)

Error: Error during creation of user.
java.lang.IllegalArgumentException: Unsupported TLS policy choice
        at com.intel.mtwilson.tls.policy.factory.TlsPolicyFactory.createTlsPolicy(TlsPolicyFactory.java:264) ~[mtwilson-tls-policy-factory-2.0.7.jar:na]
        at com.intel.mtwilson.jaxrs2.client.PropertiesTlsPolicyFactory.createTlsPolicy(PropertiesTlsPolicyFactory.java:101) ~[mtwilson-jaxrs2-client-2.0.7.jar:na]
        at com.intel.mtwilson.jaxrs2.client.JaxrsClientBuilder.tls(JaxrsClientBuilder.java:162) ~[mtwilson-jaxrs2-client-2.0.7.jar:na]
        at com.intel.mtwilson.jaxrs2.client.JaxrsClientBuilder.build(JaxrsClientBuilder.java:202) ~[mtwilson-jaxrs2-client-2.0.7.jar:na]
        at com.intel.mtwilson.jaxrs2.client.MtWilsonClient.<init>(MtWilsonClient.java:25) ~[mtwilson-jaxrs2-client-2.0.7.jar:na]
        at com.intel.mtwilson.user.management.client.jaxrs.RegisterUsers.<init>(RegisterUsers.java:26) ~[mtwilson-user-management-client-jaxrs2-2.0.7.jar:na]
        at com.intel.mtwilson.v2.client.MwClientUtil.createUserInResourceV2(MwClientUtil.java:151) ~[mtwilson-client-java7-2.0.7.jar:na]
        at com.intel.mtwilson.tag.setup.cmd.TagCreateMtWilsonClient.execute(TagCreateMtWilsonClient.java:110) [mtwilson-tag-setup-2.0.7.jar:na]
        at com.intel.dcsg.cpg.console.Main.main(Main.java:116) [cpg-console-0.2-SNAPSHOT.jar:na]

Error: Error during retrieval of certificates for writing to the key store.
java.lang.IllegalArgumentException: Unsupported TLS policy choice
        at com.intel.mtwilson.tls.policy.factory.TlsPolicyFactory.createTlsPolicy(TlsPolicyFactory.java:264) ~[mtwilson-tls-policy-factory-2.0.7.jar:na]
        at com.intel.mtwilson.jaxrs2.client.PropertiesTlsPolicyFactory.createTlsPolicy(PropertiesTlsPolicyFactory.java:101) ~[mtwilson-jaxrs2-client-2.0.7.jar:na]
        at com.intel.mtwilson.jaxrs2.client.JaxrsClientBuilder.tls(JaxrsClientBuilder.java:162) ~[mtwilson-jaxrs2-client-2.0.7.jar:na]
        at com.intel.mtwilson.jaxrs2.client.JaxrsClientBuilder.build(JaxrsClientBuilder.java:202) ~[mtwilson-jaxrs2-client-2.0.7.jar:na]
        at com.intel.mtwilson.jaxrs2.client.MtWilsonClient.<init>(MtWilsonClient.java:25) ~[mtwilson-jaxrs2-client-2.0.7.jar:na]
        at com.intel.mtwilson.attestation.client.jaxrs.CaCertificates.<init>(CaCertificates.java:32) ~[mtwilson-attestation-client-jaxrs2-2.0.7.jar:na]
        at com.intel.mtwilson.v2.client.MwClientUtil.createUserInResourceV2(MwClientUtil.java:184) ~[mtwilson-client-java7-2.0.7.jar:na]
        at com.intel.mtwilson.tag.setup.cmd.TagCreateMtWilsonClient.execute(TagCreateMtWilsonClient.java:110) [mtwilson-tag-setup-2.0.7.jar:na]
        at com.intel.dcsg.cpg.console.Main.main(Main.java:116) [cpg-console-0.2-SNAPSHOT.jar:na]
Error: User with certificate fingerprint 61fef9203096d76728cadeadf13266fe7594e9503a287234dee46e724cad2532 is not configured in the system.
Error: No translation for key MS_USER_DOES_NOT_EXISTS in bundle java.util.PropertyResourceBundle: Can't find resource for bundle java.util.PropertyResourceBundle, key MS_USER_DOES_NOT_EXISTS
Error: Message MS_USER_DOES_NOT_EXISTS args [61fef9203096d76728cadeadf13266fe7594e9503a287234dee46e724cad2532]
Error: Error during API Client update. User 61fef9203096d76728cadeadf13266fe7594e9503a287234dee46e724cad2532 is not configured in the system
Failed to approve tagservice [fingerprint 61fef9203096d76728cadeadf13266fe7594e9503a287234dee46e724cad2532]: HTTP 400 Bad Request
Error: Error while executing tag-create-mtwilson-client: Failed to approve tagservice [fingerprint 61fef9203096d76728cadeadf13266fe7594e9503a287234dee46e724cad2532]: HTTP 400 Bad Request

Thank you very much for your help

**Comment by laki9** [comment]
What do  i should need to configure for the "mtwilson.api.tls.policy.publickey.sha256" ?

**Comment by ZahediAquino** [comment]
Can you please attach full catalina.out log?

**Comment by laki9** [comment]
@ZahediAquino  Thanks very much
The first log named catalina1.zip 

 is the corresponding to above error .When i configure "mtwilson.api.tls.policy.certificate.sha256=d0 8f 07 b0 5c 6d 78 62 b9 27 48 ff 35 da 27 bf f2 03 b3 c1" in the "/etc/intel/cloudsecurity/mtwilson.properties",the value of "mtwilson.api.tls.policy.certificate.sha256" is from a test java file.It occurs the new error in the catalina2.zip 

 file. My OS is ubuntu 14.04
once again thanks.

**Comment by laki9** [comment]
[Uploading catalina1.txt…]()

**Comment by laki9** [comment]
@ZahediAquino 
[Uploading catalina1.txt…]()
[Uploading catalina2.txt…]()

**Comment by laki9** [comment]
[catalina1.txt](https://github.com/opencit/opencit/files/351320/catalina1.txt)
[catalina2.txt](https://github.com/opencit/opencit/files/351322/catalina2.txt)
@ZahediAquino

**Comment by ZahediAquino** [comment]
-mtwilson.api.tls.policy.certificate.sha256 is not a valid property, we only support SHA1. Also, the spaces would need to be removed from a SHA1 value. So stick to mtwilson.api.tls.policy.certificate.sha1 for now.
-For your new error, can you try on a new OS Image, we might need to debug there on what to do with previous failed installation cleanup. I will have to check and get back to you on this.

**Comment by laki9** [comment]
I follow your  guidance to append the 'mtwilson.api.tls.policy.certificate.sha1=d08f07b05c6d7862b92748ff35da27bff203b3c1' in the /etc/intel/cloudsecurity/mtwilson.properties ,it will be the same as the above error of catalina2.txt.Should i configure the property of d08f07b05c6d7862b92748ff35da27bff203b3c1? Next time,i should need to change a new OS Image.
Thanks.

**Comment by ZahediAquino** [comment]
Were you able to get past the issue using sha1?

**Comment by laki9** [comment]
I configure the sha1 in the /etc/intel/cloudsecurity/mtwilson.properties,there will still be above problem same as catalina2.txt 
Thanks very much
@ZahediAquino

**Comment by laki9** [comment]
not working on this project any more
