### ISSUE TITLE
Error installing tagent on CentOS 7.2 host.

### ISSUE THREAD

**Issue by choudhary01** [opencit/opencit#24]
The product guide said there is separate installer for RHEL host but I could find in installation target. I anyway tried  mtwilson-trustagent-2.2-SNAPSHOT.bin.  Is this correct ?

I am seeing following error which seems that host is not able to communicate with server.
I am able to open CIT portal for external browser which proves that server 8443 port is open and responding. Why it s not server TLS certs to host ?

https://172.18.42.78:8443/mtwilson/v1
{"error_code":"SYSTEM_ERROR","error_message":"Resource not found"}

https://172.30.21.178:1443/v2/host
<host_info>
<timestamp>1477273674090</timestamp>
<errorCode>OK</errorCode>
<errorMessage>OK</errorMessage>
<osName>CentOS</osName>
<osVersion>7.2.1511</osVersion>
<biosOem>American Megatrends Inc.</biosOem>
<biosVersion>5.6.5</biosVersion>
<processorInfo>F2 06 03 00 FF FB EB BF</processorInfo>
<hardwareUuid>03000200-0400-0500-0006-000700080009</hardwareUuid>
<tpmVersion>2.0</tpmVersion>
<pcrBanks>SHA1</pcrBanks>
</host_info>

Starting the process to configure the username and password.
Created user admin
Added permissions _:_
Error: Setup task error: null
Error: Cannot run DownloadMtWilsonTlsCertificate: Setup error
Error: Setup task error: java.net.ConnectException: Connection timed out
Error: Cannot run DownloadMtWilsonPrivacyCACertificate: Setup error
Error: Setup task error: java.net.ConnectException: Connection timed out
Error: Cannot run DownloadMtWilsonSamlCertificate: Setup error
Error: Cannot configure TPM Endorsements API client
com.intel.mtwilson.tls.policy.factory.TlsPolicyDescriptorInvalidException: java.lang.IllegalArgumentException: TLS policy descriptor does not contain any certificates
        at com.intel.mtwilson.tls.policy.factory.TlsPolicyFactoryUtil.createTlsPolicy(TlsPolicyFactoryUtil.java:176) ~[mtwilson-util-tls-policy-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.jaxrs2.client.PropertiesTlsPolicyFactory.createTlsPolicy(PropertiesTlsPolicyFactory.java:97) ~[mtwilson-util-jaxrs2-client-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.jaxrs2.client.JaxrsClientBuilder.tls(JaxrsClientBuilder.java:189) ~[mtwilson-util-jaxrs2-client-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.jaxrs2.client.JaxrsClientBuilder.build(JaxrsClientBuilder.java:253) ~[mtwilson-util-jaxrs2-client-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.jaxrs2.client.MtWilsonClient.<init>(MtWilsonClient.java:25) ~[mtwilson-util-jaxrs2-client-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.tpm.endorsement.client.jaxrs.TpmEndorsements.<init>(TpmEndorsements.java:31) ~[mtwilson-tpm-endorsement-client-jaxrs2-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.trustagent.setup.RequestEndorsementCertificate.configure(RequestEndorsementCertificate.java:115) ~[mtwilson-trustagent-setup-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.setup.AbstractSetupTask.isConfigured(AbstractSetupTask.java:136) [mtwilson-setup-ext-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.setup.console.cmd.Setup.execute(Setup.java:190) [mtwilson-setup-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.setup.console.cmd.Setup.execute(Setup.java:118) [mtwilson-setup-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.launcher.console.Dispatcher.run(Dispatcher.java:100) [mtwilson-launcher-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.launcher.console.Main.main(Main.java:60) [mtwilson-launcher-2.2-SNAPSHOT.jar:na]
Caused by: java.lang.IllegalArgumentException: TLS policy descriptor does not contain any certificates
        at com.intel.mtwilson.tls.policy.creator.impl.CertificateTlsPolicyCreator.getCertificateRepository(CertificateTlsPolicyCreator.java:48) ~[mtwilson-util-tls-policy-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.tls.policy.creator.impl.CertificateTlsPolicyCreator.createTlsPolicy(CertificateTlsPolicyCreator.java:30) ~[mtwilson-util-tls-policy-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.tls.policy.creator.impl.CertificateTlsPolicyCreator.createTlsPolicy(CertificateTlsPolicyCreator.java:23) ~[mtwilson-util-tls-policy-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.tls.policy.factory.TlsPolicyFactoryUtil.createTlsPolicy(TlsPolicyFactoryUtil.java:167) ~[mtwilson-util-tls-policy-2.2-SNAPSHOT.jar:na]
        ... 11 common frames omitted
Error: Cannot configure TPM Endorsements API client
com.intel.mtwilson.tls.policy.factory.TlsPolicyDescriptorInvalidException: java.lang.IllegalArgumentException: TLS policy descriptor does not contain any certificates
        at com.intel.mtwilson.tls.policy.factory.TlsPolicyFactoryUtil.createTlsPolicy(TlsPolicyFactoryUtil.java:176) ~[mtwilson-util-tls-policy-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.jaxrs2.client.PropertiesTlsPolicyFactory.createTlsPolicy(PropertiesTlsPolicyFactory.java:97) ~[mtwilson-util-jaxrs2-client-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.jaxrs2.client.JaxrsClientBuilder.tls(JaxrsClientBuilder.java:189) ~[mtwilson-util-jaxrs2-client-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.jaxrs2.client.JaxrsClientBuilder.build(JaxrsClientBuilder.java:253) ~[mtwilson-util-jaxrs2-client-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.jaxrs2.client.MtWilsonClient.<init>(MtWilsonClient.java:25) ~[mtwilson-util-jaxrs2-client-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.tpm.endorsement.client.jaxrs.TpmEndorsements.<init>(TpmEndorsements.java:31) ~[mtwilson-tpm-endorsement-client-jaxrs2-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.trustagent.setup.RequestEndorsementCertificate.configure(RequestEndorsementCertificate.java:115) ~[mtwilson-trustagent-setup-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.setup.AbstractSetupTask.isConfigured(AbstractSetupTask.java:136) [mtwilson-setup-ext-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.setup.AbstractSetupTask.run(AbstractSetupTask.java:146) [mtwilson-setup-ext-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.setup.console.cmd.Setup.execute(Setup.java:214) [mtwilson-setup-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.setup.console.cmd.Setup.execute(Setup.java:118) [mtwilson-setup-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.launcher.console.Dispatcher.run(Dispatcher.java:100) [mtwilson-launcher-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.launcher.console.Main.main(Main.java:60) [mtwilson-launcher-2.2-SNAPSHOT.jar:na]
Caused by: java.lang.IllegalArgumentException: TLS policy descriptor does not contain any certificates
        at com.intel.mtwilson.tls.policy.creator.impl.CertificateTlsPolicyCreator.getCertificateRepository(CertificateTlsPolicyCreator.java:48) ~[mtwilson-util-tls-policy-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.tls.policy.creator.impl.CertificateTlsPolicyCreator.createTlsPolicy(CertificateTlsPolicyCreator.java:30) ~[mtwilson-util-tls-policy-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.tls.policy.creator.impl.CertificateTlsPolicyCreator.createTlsPolicy(CertificateTlsPolicyCreator.java:23) ~[mtwilson-util-tls-policy-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.tls.policy.factory.TlsPolicyFactoryUtil.createTlsPolicy(TlsPolicyFactoryUtil.java:167) ~[mtwilson-util-tls-policy-2.2-SNAPSHOT.jar:na]
        ... 12 common frames omitted
Error: Error from RequestEndorsementCertificate: Configuration required
Warning: Configuring RequestEndorsementCertificate: [com.intel.mtwilson.util.validation.faults.Thrown: Cannot configure TPM Endorsements API client]
Warning: Configuring RequestEndorsementCertificate: [com.intel.mtwilson.util.validation.faults.Thrown: Cannot configure CA Certificates API client]
Error: Error while executing setup: Encountered errors during setup
Register TPM password with service to support asset tag automation? [y/n] [y] y
Username: [pcaadmin] pcaadmin
Password: [*******_] ***_****
Error: Setup task error: java.net.ConnectException: Connection timed out
Error: Cannot run RegisterTpmPassword: Setup error
Error: Error while executing setup: Encountered errors during setup
Error: Error while executing import-config: File contents are already encrypted
Usage: import-config <infile|--in=infile|--stdin> [--env-password=PASSWORD_VAR]
Started trust agent
Redirecting to /bin/systemctl restart  monit.service

**Comment by 19LukaModric** [comment]
Did you force clear the tpm before installation?

**Comment by ryansavino** [comment]
Please paste the contents of your trustagent.env file

**Comment by choudhary01** [comment]
[root@centos7 ~]# cat trustagent.env
MTWILSON_API_URL=https://172.18.42.78:8443/mtwilson/v2
MTWILSON_API_USERNAME=pcaadmin
MTWILSON_API_PASSWORD=password
MTWILSON_TLS_CERT_SHA256=b81debc9fac3e1f0cd3fa446a4d087b526aedcce9a391327cdf201afd7093c4f
REGISTER_TPM_PASSWORD=y
TPM_OWNER_SECRET=0102030405060708091011121314151617181920
TRUSTAGENT_LOGIN_REGISTER=true
TRUSTAGENT_KEYSTORE_PASSWORD=password
TRUSTAGENT_ADMIN_PASSWORD=password
TRUSTAGENT_ADMIN_USERNAME=admin

**Comment by ryansavino** [comment]
Please enable DEBUG logging (logging configuration file: /opt/trustagent/configuration/logback.xml) and provide logfile:
1. remove or comment any logger starting with "com.intel"
    i.e.: \<logger name="com.intel.dcsg.cpg" level="INFO"/>
2. change root level logger to DEBUG
    i.e.: \<root level="${TRUSTAGENT_LOG_LEVEL:-DEBUG}">
3. tagent restart
4. tagent setup
5. attach logfile for analysis: /opt/trustagent/logs/trustagent.log

Also, please provide the output of running 'txt-stat'.

It would be good to verify the attestation service TLS SHA256, if you haven't already.
