### ISSUE TITLE
Unexpected error in configureWhiteListFromCustomData: HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by JiaJianZ** [opencit/opencit#35]
Hello
I install mtwilson server and trustAgent(tpm2.0) .When I import Whitelist from Trusted Host .I get some error as follows:

2017-02-16 14:36:30,269 INFO [http-bio-8443-exec-18] c.i.m.s.SecurityFilter [SecurityFilter.java:225] SecurityFilter >>
org.apache.catalina.session.StandardSessionFacade@3a58e265----/getData/uploadWhiteListConfiguration.html
whiteListConfigVO>>WhiteListConfig [biosWhiteList=true, vmmWhiteList=true, biosWLTarget=BIOS_OEM, vmmWLTarget=VMM_OEM, biosPCRs=, vmmPCRs=, hostLocation=null, registerHost=true]
2017-02-16 14:36:30,276 INFO [http-bio-8443-exec-18] c.i.m.S.ManagementConsoleServicesImpl [ManagementConsoleServicesImpl.java:70] ManagementConsoleServicesImpl.saveWhiteListConfiguration >>
2017-02-16 14:36:30,294 WARN [http-bio-8443-exec-15] c.i.m.s.a.h.IniHostRealm [IniHostRealm.java:66] IniHostRealm.allow is not set; host-based authentication disabled
2017-02-16 14:36:30,295 WARN [http-bio-8443-exec-15] c.i.m.s.LoggingAtLeastOneSuccessfulStrategy [LoggingAtLeastOneSuccessfulStrategy.java:70] no principal collection or realm names
2017-02-16 14:36:30,295 WARN [http-bio-8443-exec-15] c.i.m.s.a.x.X509AuthenticationFilter [X509AuthenticationFilter.java:277] Authorization is missing realm
2017-02-16 14:36:30,318 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-02-16 14:36:30,318 WARN [http-bio-8443-exec-15] c.i.m.s.a.h.IniHostRealm [IniHostRealm.java:48] IniHostRealm.allow is not set; host-based authorization disabled
2017-02-16 14:36:30,319 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-02-16 14:36:30,325 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-02-16 14:36:30,325 WARN [http-bio-8443-exec-15] c.i.m.s.a.h.IniHostRealm [IniHostRealm.java:48] IniHostRealm.allow is not set; host-based authorization disabled
2017-02-16 14:36:30,325 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-02-16 14:36:30,330 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-02-16 14:36:30,330 WARN [http-bio-8443-exec-15] c.i.m.s.a.h.IniHostRealm [IniHostRealm.java:48] IniHostRealm.allow is not set; host-based authorization disabled
2017-02-16 14:36:30,330 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-02-16 14:36:30,335 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-02-16 14:36:30,335 WARN [http-bio-8443-exec-15] c.i.m.s.a.h.IniHostRealm [IniHostRealm.java:48] IniHostRealm.allow is not set; host-based authorization disabled
2017-02-16 14:36:30,335 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-02-16 14:36:30,340 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-02-16 14:36:30,340 WARN [http-bio-8443-exec-15] c.i.m.s.a.h.IniHostRealm [IniHostRealm.java:48] IniHostRealm.allow is not set; host-based authorization disabled
2017-02-16 14:36:30,340 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-02-16 14:36:30,345 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-02-16 14:36:30,345 WARN [http-bio-8443-exec-15] c.i.m.s.a.h.IniHostRealm [IniHostRealm.java:48] IniHostRealm.allow is not set; host-based authorization disabled
2017-02-16 14:36:30,346 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-02-16 14:36:30,352 WARN [http-bio-8443-exec-15] c.i.m.t.p.f.TlsPolicyFactory [TlsPolicyFactory.java:212] Invalid tlsPolicyId: 
2017-02-16 14:36:30,352 INFO [http-bio-8443-exec-15] c.i.d.c.j.PersistenceManager [PersistenceManager.java:77] PersistenceManager is configured with 3 factories in getEntityManagerFactory
2017-02-16 14:36:30,363 INFO [http-bio-8443-exec-15] c.i.d.c.j.PersistenceManager [PersistenceManager.java:77] PersistenceManager is configured with 3 factories in getEntityManagerFactory
2017-02-16 14:36:30,561 ERROR [http-bio-8443-exec-15] c.i.m.m.b.HostBO [HostBO.java:779] Unexpected error in configureWhiteListFromCustomData: HTTP 401 Unauthorized
2017-02-16 14:36:30,562 ERROR [http-bio-8443-exec-15] c.i.m.m.b.HostBO [HostBO.java:996] Error during white list configuration. MS_HOST_COMMUNICATION_ERROR :Error during communication with the host. Please verify the host parameters. NotAuthorizedException.
2017-02-16 14:36:30,566 ERROR [http-bio-8443-exec-18] c.i.m.S.ManagementConsoleServicesImpl [ManagementConsoleServicesImpl.java:126] Failed to configure whitelist: Error during communication with the host. Please verify the host parameters. NotAuthorizedException. [MS_HOST_COMMUNICATION_ERROR] 
com.intel.mtwilson.api.ApiException: Error during communication with the host. Please verify the host parameters. NotAuthorizedException. [MS_HOST_COMMUNICATION_ERROR] 
        at com.intel.mtwilson.ApiClient.error(ApiClient.java:475)
        at com.intel.mtwilson.ApiClient.content(ApiClient.java:515)
        at com.intel.mtwilson.ApiClient.text(ApiClient.java:532)
        at com.intel.mtwilson.ApiClient.configureWhiteList(ApiClient.java:1534)
        at com.intel.mountwilson.Service.ManagementConsoleServicesImpl.saveWhiteListConfiguration(ManagementConsoleServicesImpl.java:123)
        at com.intel.mountwilson.controller.ManagementConsoleDataController.uploadWhiteListConfiguration(ManagementConsoleDataController.java:312)
        at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.servlet.mvc.multiaction.MultiActionController.invokeNamedMethod(MultiActionController.java:471)
        at org.springframework.web.servlet.mvc.multiaction.MultiActionController.handleRequestInternal(MultiActionController.java:408)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)2017-02-16 14:36:30,569 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.

        at com.intel.mountwilson.security.SecurityFilter.doFilter(SecurityFilter.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)2017-02-16 14:36:30,571 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
2017-02-16 14:36:30,572 INFO [http-bio-8443-exec-15] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-02-16 14:36:30,898 INFO [pool-1-thread-1] c.i.d.c.j.PersistenceManager [PersistenceManager.java:77] PersistenceManager is configured with 3 factories in getEntityManagerFactory
2017-02-16 14:36:30,898 INFO [pool-1-thread-1] c.i.m.a.c.TblSamlAssertionJpaController [TblSamlAssertionJpaController.java:268] AutoRefreshTrust: findHostnamesWithExpiredCache
2017-02-16 14:36:30,899 INFO [pool-1-thread-1] c.i.m.a.c.TblSamlAssertionJpaController [TblSamlAssertionJpaController.java:276] AutoRefreshTrust: Query hosts whose SAML was created after 2017-02-16 13:41:30. Current time is 2017-02-16 14:36:30.
2017-02-16 14:36:30,902 INFO [pool-1-thread-1] c.i.m.p.AutoRefreshTrust [AutoRefreshTrust.java:71] AutoRefreshTrust: No hosts for bulk refresh
2017-02-16 14:36:30,902 INFO [pool-1-thread-1] c.i.m.p.AutoRefreshTrust [AutoRefreshTrust.java:75] AutoRefreshTrust: Auto refresh thread would sleep for 120 seconds.
2017-02-16 14:38:30,903 INFO [pool-1-thread-1] c.i.d.c.j.PersistenceManager [PersistenceManager.java:77] PersistenceManager is configured with 3 factories in getEntityManagerFactory
2017-02-16 14:38:30,904 INFO [pool-1-thread-1] c.i.m.a.c.TblSamlAssertionJpaController [TblSamlAssertionJpaController.java:268] AutoRefreshTrust: findHostnamesWithExpiredCache
2017-02-16 14:38:30,905 INFO [pool-1-thread-1] c.i.m.a.c.TblSamlAssertionJpaController [TblSamlAssertionJpaController.java:276] AutoRefreshTrust: Query hosts whose SAML was created after 2017-02-16 13:43:30. Current time is 2017-02-16 14:38:30.
2017-02-16 14:38:30,909 INFO [pool-1-thread-1] c.i.m.p.AutoRefreshTrust [AutoRefreshTrust.java:71] AutoRefreshTrust: No hosts for bulk refresh
2017-02-16 14:38:30,909 INFO [pool-1-thread-1] c.i.m.p.AutoRefreshTrust [AutoRefreshTrust.java:75] AutoRefreshTrust: Auto refresh thread would sleep for 120 seconds.

I would really appreciate any help

Thanks

**Comment by ryansavino** [comment]
I would make sure your trustagent installation didn't have any errors.

Check your firewall rules. Attestation service has default port 8443 and trustagent has default port 1443.

Enable debug logging for attestation service and trustagent and also provide the trustagent log (/opt/trustagent/logs/trustagent.log) so that we will be able to assist better.

**Comment by JiaJianZ** [comment]
I reinstall the trustagent and the  problem didn't appear in  
Thanks
