### ISSUE TITLE
 Import the  Whitelist from Trusted Host errors

### ISSUE THREAD

**Issue by yankunsam** [opencit/opencit#46]
![screenshot from 2017-03-16 15 52 45](https://cloud.githubusercontent.com/assets/16130147/23986734/a4f50242-0a60-11e7-9553-d8fd70d3b88f.png)
There is no issues when I install agent.
Installation Environment : qemu_system_x86_64 --enable-kvm Vtpm
                                       ubuntu14.04 
Error during communication with the host. Please verify the host parameters. NotAuthorizedException. [MS_HOST_COMMUNICATION_ERROR] [3201

**Comment by ZahediAquino** [comment]
Can you please enable DEBUG mode? and attach both Attestation Service (catalina.out) and Trust Agent (trustagent.log) logs ?

https://github.com/opencit/opencit/wiki/FAQ#how-do-i-enable-debug-mode

**Comment by yankunsam** [comment]
Can I have your email.The file is too big.Actually ,the log files contains "2017-03-17 11:33:45,364 DEBUG [qtp2100598662-22] c.i.m.t.c.hostinfo.HostInfoCmd - Bios OEM: American Megatrends Inc."

Is it helpfule?
/****trustagent.log****/
2017-03-17 11:44:29,074 DEBUG [qtp2100598662-51] c.i.m.s.RepeatableRequestFilter - ServletInputStream markSupported? false
/****catalina.out****/
2017-03-17 12:03:26,561 WARN [http-bio-8443-exec-11] c.i.m.s.a.h.IniHostRealm [IniHostRealm.java:66] IniHostRealm.allow is not set; host-based authentication disabled

2017-03-17 12:07:00,967 INFO [http-bio-8443-exec-9] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.

**Comment by ryansavino** [comment]
Where is the stack trace? Maybe post just the tail end of the log file.

**Comment by zhq0918** [comment]
2017-04-21 15:47:41,456 DEBUG [qtp951175664-63] c.i.m.s.a.p.HttpBasicAuthenticationFilter - executeLogin subject org.apache.shiro.web.subject.support.WebDelegatingSubject
2017-04-21 15:47:41,456 DEBUG [qtp951175664-63] c.i.m.shiro.file.FilePasswordRealm - doGetAuthenticationInfo for username admin
2017-04-21 15:47:41,456 DEBUG [qtp951175664-63] c.i.m.shiro.file.FilePasswordRealm - doGetAuthenticationInfo found user admin
2017-04-21 15:47:41,456 DEBUG [qtp951175664-63] c.i.m.s.a.p.PasswordCredentialsMatcher - doCredentialsMatch with token org.apache.shiro.authc.UsernamePasswordToken - admin, rememberMe=false (xx.xx.xx.xx) and info com.intel.mtwilson.shiro.UsernameWithPermissions@74176fe4
2017-04-21 15:47:41,458 DEBUG [qtp951175664-63] c.i.m.s.a.p.HttpBasicAuthenticationFilter - executeLogin subject login failed {}
org.apache.shiro.authc.IncorrectCredentialsException: Submitted credentials for token [org.apache.shiro.authc.UsernamePasswordToken - admin, rememberMe=false (10.130.179.159)] did not match the expected credentials.
	at org.apache.shiro.realm.AuthenticatingRealm.assertCredentialsMatch(AuthenticatingRealm.java:600) ~[shiro-core-1.2.2.jar:1.2.2]
	at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:578) ~[shiro-core-1.2.2.jar:1.2.2]
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doSingleRealmAuthentication(ModularRealmAuthenticator.java:180) ~[shiro-core-1.2.2.jar:1.2.2]
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:267) ~[shiro-core-1.2.2.jar:1.2.2]
	at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198) ~[shiro-core-1.2.2.jar:1.2.2]
	at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106) ~[shiro-core-1.2.2.jar:1.2.2]
	at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270) ~[shiro-core-1.2.2.jar:1.2.2]
	at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256) [shiro-core-1.2.2.jar:1.2.2]
	at com.intel.mtwilson.shiro.authc.password.HttpBasicAuthenticationFilter.executeLogin(HttpBasicAuthenticationFilter.java:39) ~[mtwilson-shiro-util-2.2-SNAPSHOT.jar:na]
	at org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter.onAccessDenied(BasicHttpAuthenticationFilter.java:190) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.filter.AccessControlFilter.onAccessDenied(AccessControlFilter.java:133) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.filter.AccessControlFilter.onPreHandle(AccessControlFilter.java:162) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.filter.PathMatchingFilter.isFilterChainContinued(PathMatchingFilter.java:203) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.filter.PathMatchingFilter.preHandle(PathMatchingFilter.java:178) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:131) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.2.2.jar:1.2.2]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.2.2.jar:1.2.2]
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) [shiro-core-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1556) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
	at com.intel.mtwilson.servlet.RepeatableRequestFilter.doFilter(RepeatableRequestFilter.java:46) [mtwilson-http-servlets-2.2-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1548) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:524) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568) [jetty-security-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1110) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:453) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1044) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.Server.handle(Server.java:459) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505) [jetty-io-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:594) [jetty-util-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:525) [jetty-util-9.1.0.RC2.jar:9.1.0.RC2]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]

**Comment by ge0rgi** [comment]
Did you manage to resolve this? I am getting the same error today:
tail catalina.out:

`2017-06-16 17:47:30,215 INFO [http-bio-8443-exec-22] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-06-16 17:47:30,216 ERROR [http-bio-8443-exec-19] c.i.m.S.ManagementConsoleServicesImpl [ManagementConsoleServicesImpl.java:126] Failed to configure whitelist: Error during communication with the host. Please verify the host parameters. NotAuthorizedException. [MS_HOST_COMMUNICATION_ERROR] 
com.intel.mtwilson.api.ApiException: Error during communication with the host. Please verify the host parameters. NotAuthorizedException. [MS_HOST_COMMUNICATION_ERROR] 
	at com.intel.mtwilson.ApiClient.error(ApiClient.java:475)
	at com.intel.mtwilson.ApiClient.content(ApiClient.java:515)
	at com.intel.mtwilson.ApiClient.text(ApiClient.java:532)
	at com.intel.mtwilson.ApiClient.configureWhiteList(ApiClient.java:1534)
	at com.intel.mountwilson.Service.ManagementConsoleServicesImpl.saveWhiteListConfiguration(ManagementConsoleServicesImpl.java:123)
	at com.intel.mountwilson.controller.ManagementConsoleDataController.uploadWhiteListConfiguration(ManagementConsoleDataController.java:312)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.servlet.mvc.multiaction.MultiActionController.invokeNamedMethod(MultiActionController.java:471)
	at org.springframework.web.servlet.mvc.multiaction.MultiActionController.handleRequestInternal(MultiActionController.java:408)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.intel.mountwilson.security.SecurityFilter.doFilter(SecurityFilter.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
2017-06-16 17:47:48,658 INFO [pool-1-thread-1] c.i.d.c.j.PersistenceManager [PersistenceManager.java:77] PersistenceManager is configured with 3 factories in getEntityManagerFactory
2017-06-16 17:47:48,659 INFO [pool-1-thread-1] c.i.m.a.c.TblSamlAssertionJpaController [TblSamlAssertionJpaController.java:268] AutoRefreshTrust: findHostnamesWithExpiredCache
2017-06-16 17:47:48,660 INFO [pool-1-thread-1] c.i.m.a.c.TblSamlAssertionJpaController [TblSamlAssertionJpaController.java:276] AutoRefreshTrust: Query hosts whose SAML was created after 2017-06-16 16:52:48. Current time is 2017-06-16 17:47:48.
2017-06-16 17:47:48,662 INFO [pool-1-thread-1] c.i.m.p.AutoRefreshTrust [AutoRefreshTrust.java:71] AutoRefreshTrust: No hosts for bulk refresh
2017-06-16 17:47:48,663 INFO [pool-1-thread-1] c.i.m.p.AutoRefreshTrust [AutoRefreshTrust.java:75] AutoRefreshTrust: Auto refresh thread would sleep for 120 seconds.
`


tail trustagent.log:
`2017-06-16 17:28:23,588 DEBUG [main] c.i.d.c.t.p.i.CertificateTlsPolicy - isCertificateTrusted: sha1 93f006da98ce70bec2b914622858380f910d2c45
2017-06-16 17:28:23,588 DEBUG [main] c.i.d.c.t.p.i.CertificateTlsPolicy - isCertificateTrusted: trusted sha1 93f006da98ce70bec2b914622858380f910d2c45
2017-06-16 17:28:23,751 INFO  [main] c.i.m.t.setup.LoginRegister - Successfully registered the host access information with attestation service.
2017-06-16 17:28:23,767 DEBUG [main] c.i.d.c.c.k.p.PBKDFCryptoCodec - cipher AES/CBC/PKCS5Padding
2017-06-16 17:29:34,264 DEBUG [qtp1823499311-20] c.i.m.s.RepeatableRequestFilter - ServletRequest class org.eclipse.jetty.server.Request
2017-06-16 17:29:34,264 DEBUG [qtp1823499311-20] c.i.m.s.RepeatableRequestFilter - Wrapping ServletRequest with RepeatableServletRequest
2017-06-16 17:41:46,325 DEBUG [qtp1823499311-33] c.i.m.s.RepeatableRequestFilter - ServletRequest class org.eclipse.jetty.server.Request
2017-06-16 17:41:46,325 DEBUG [qtp1823499311-33] c.i.m.s.RepeatableRequestFilter - Wrapping ServletRequest with RepeatableServletRequest
2017-06-16 17:48:10,567 DEBUG [qtp1823499311-39] c.i.m.s.RepeatableRequestFilter - ServletRequest class org.eclipse.jetty.server.Request
2017-06-16 17:48:10,567 DEBUG [qtp1823499311-39] c.i.m.s.RepeatableRequestFilter - Wrapping ServletRequest with RepeatableServletRequest
`
I see there are username and password fields in the form. How do I know what credentials I need to use?

**Comment by priyanknarvekar** [comment]
Not sure, if you set the credentials, 
I ran into a similar issue, setting the credentials fixed it,
Subsequently I ran into a different issue, with an internal server error during import through #64 

if you didnt set custom username and password during the trust agent installation, 
the default is admin and password is randomly generated and stored in 
`/opt/trustagent/configuration/private/password.txt`
These steps are missing in the product guide for importing the Linux KVM host, but they were there for others.
