### ISSUE TITLE
Import from trusted host fails with error

### ISSUE THREAD

**Issue by lals1** [opencit/opencit#66]
Hi

I am not able to register host using option import from trusted host in OpenCIT. The trust agent host is running ubuntu 16.04 and TPM2.0. Trust agent is installed successfully and running. CIT dashboard shows this error when registering host:

Error during communication with the host. Please verify the host parameters. BadRequestException. [MS_HOST_COMMUNICATION_ERROR] [3201]

I have enabled debug logging on tagent. Below is tagent log file showing error related to VMM name and version. There is KVM hypervisor installed already.

Any help??

_2017-08-18 17:50:28,740 DEBUG [qtp1666392491-86] c.i.m.s.RepeatableRequestFilter - ServletRequest class org.eclipse.jetty.server.Request
2017-08-18 17:50:28,741 DEBUG [qtp1666392491-86] c.i.m.s.RepeatableRequestFilter - Wrapping ServletRequest with RepeatableServletRequest
2017-08-18 17:50:28,741 DEBUG [qtp1666392491-86] c.i.m.s.a.p.HttpBasicAuthenticationFilter - executeLogin subject org.apache.shiro.web.subject.support.WebDelegatingSubject
2017-08-18 17:50:28,741 DEBUG [qtp1666392491-86] c.i.m.shiro.file.FilePasswordRealm - doGetAuthenticationInfo for username admin
2017-08-18 17:50:28,742 DEBUG [qtp1666392491-86] c.i.m.shiro.file.FilePasswordRealm - doGetAuthenticationInfo found user admin
2017-08-18 17:50:28,742 DEBUG [qtp1666392491-86] c.i.m.s.a.p.PasswordCredentialsMatcher - doCredentialsMatch with token org.apache.shiro.authc.UsernamePasswordToken - admin, rememberMe=false (10.22.215.237) and info com.intel.mtwilson.shiro.UsernameWithPermissions@57ed07c5
2017-08-18 17:50:28,743 DEBUG [qtp1666392491-86] c.i.m.s.RepeatableRequestFilter - ServletInputStream markSupported? false
2017-08-18 17:50:28,745 DEBUG [qtp1666392491-86] c.intel.mtwilson.util.exec.ExecUtil - Executing command: /opt/trustagent/bin/tagent with arguments: [system-info, lsb_release -a]
2017-08-18 17:50:28,788 DEBUG [qtp1666392491-86] c.i.m.t.c.hostinfo.HostInfoCmd - command stdout: Distributor ID:       Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

2017-08-18 17:50:28,788 DEBUG [qtp1666392491-86] c.i.m.t.c.hostinfo.HostInfoCmd - OS Name: Ubuntu
2017-08-18 17:50:28,788 DEBUG [qtp1666392491-86] c.i.m.t.c.hostinfo.HostInfoCmd - OS Version: 16.04
2017-08-18 17:50:28,788 DEBUG [qtp1666392491-86] c.intel.mtwilson.util.exec.ExecUtil - Executing command: /opt/trustagent/bin/tagent with arguments: [system-info, dmidecode, -s bios-vendor]
2017-08-18 17:50:28,824 DEBUG [qtp1666392491-86] c.i.m.t.c.hostinfo.HostInfoCmd - command stdout: HP

2017-08-18 17:50:28,824 DEBUG [qtp1666392491-86] c.i.m.t.c.hostinfo.HostInfoCmd - Bios OEM: HP
2017-08-18 17:50:28,824 DEBUG [qtp1666392491-86] c.intel.mtwilson.util.exec.ExecUtil - Executing command: /opt/trustagent/bin/tagent with arguments: [system-info, dmidecode, -s bios-version]
2017-08-18 17:50:28,857 DEBUG [qtp1666392491-86] c.i.m.t.c.hostinfo.HostInfoCmd - command stdout: N25 Ver. 02.07

2017-08-18 17:50:28,857 DEBUG [qtp1666392491-86] c.i.m.t.c.hostinfo.HostInfoCmd - Bios Version: N25 Ver. 02.07
2017-08-18 17:50:28,857 DEBUG [qtp1666392491-86] c.intel.mtwilson.util.exec.ExecUtil - Executing command: /opt/trustagent/bin/tagent with arguments: [system-info, virsh version]
2017-08-18 17:50:28,889 DEBUG [qtp1666392491-86] c.i.m.t.c.hostinfo.HostInfoCmd - command stdout:
2017-08-18 17:50:28,889 INFO  [qtp1666392491-86] c.i.m.t.c.hostinfo.HostInfoCmd - getVmmAndVersion: empty virsh version file, assuming no VMM installed
2017-08-18 17:50:28,889 DEBUG [qtp1666392491-86] c.i.m.t.c.hostinfo.HostInfoCmd - Error while getting OS details
com.intel.mountwilson.common.TAException: Not able to get VMM name and version.
        at com.intel.mountwilson.trustagent.commands.hostinfo.HostInfoCmd.getVmmAndVersion(HostInfoCmd.java:205) ~[mtwilson-trustagent-ws-v2-2.2-SNAPSHOT.jar:na]
        at com.intel.mountwilson.trustagent.commands.hostinfo.HostInfoCmd.execute(HostInfoCmd.java:45) ~[mtwilson-trustagent-ws-v2-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.trustagent.ws.v2.Host.getHostInformation(Host.java:46) [mtwilson-trustagent-ws-v2-2.2-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151) [jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171) [jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195) [jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104) [jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:367) [jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349) [jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106) [jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259) [jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.4.1.jar:na]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.4.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.4.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.4.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.4.1.jar:na]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318) [jersey-common-2.4.1.jar:na]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236) [jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:983) [jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:361) [jersey-container-servlet-core-2.4.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:372) [jersey-container-servlet-core-2.4.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335) [jersey-container-servlet-core-2.4.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:218) [jersey-container-servlet-core-2.4.1.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1568) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.2.2.jar:1.2.2]
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.2.2.jar:1.2.2]
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) [shiro-core-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1556) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
        at com.intel.mtwilson.servlet.RepeatableRequestFilter.doFilter(RepeatableRequestFilter.java:46) [mtwilson-http-servlets-2.2-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1548) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:524) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568) [jetty-security-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1110) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:453) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1044) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.Server.handle(Server.java:459) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505) [jetty-io-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:594) [jetty-util-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:525) [jetty-util-9.1.0.RC2.jar:9.1.0.RC2]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
2017-08-18 17:50:28,890 DEBUG [qtp1666392491-86] c.i.mtwilson.util.ThrowableMapper - ThrowableMapper toResponse
com.intel.mountwilson.common.TAException: Error while getting OS details.
        at com.intel.mountwilson.trustagent.commands.hostinfo.HostInfoCmd.execute(HostInfoCmd.java:53) ~[mtwilson-trustagent-ws-v2-2.2-SNAPSHOT.jar:na]
        at com.intel.mtwilson.trustagent.ws.v2.Host.getHostInformation(Host.java:46) ~[mtwilson-trustagent-ws-v2-2.2-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151) ~[jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171) ~[jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195) ~[jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104) ~[jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:367) ~[jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349) ~[jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106) ~[jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259) ~[jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.4.1.jar:na]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.4.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.4.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.4.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.4.1.jar:na]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318) [jersey-common-2.4.1.jar:na]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236) [jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:983) [jersey-server-2.4.1.jar:na]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:361) [jersey-container-servlet-core-2.4.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:372) [jersey-container-servlet-core-2.4.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335) [jersey-container-servlet-core-2.4.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:218) [jersey-container-servlet-core-2.4.1.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1568) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.2.2.jar:1.2.2]
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.2.2.jar:1.2.2]
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) [shiro-core-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.2.2.jar:1.2.2]
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1556) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
        at com.intel.mtwilson.servlet.RepeatableRequestFilter.doFilter(RepeatableRequestFilter.java:46) [mtwilson-http-servlets-2.2-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1548) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:524) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568) [jetty-security-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1110) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:453) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1044) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.Server.handle(Server.java:459) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505) [jetty-io-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:594) [jetty-util-9.1.0.RC2.jar:9.1.0.RC2]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:525) [jetty-util-9.1.0.RC2.jar:9.1.0.RC2]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
Caused by: com.intel.mountwilson.common.TAException: Not able to get VMM name and version.
        at com.intel.mountwilson.trustagent.commands.hostinfo.HostInfoCmd.getVmmAndVersion(HostInfoCmd.java:205) ~[mtwilson-trustagent-ws-v2-2.2-SNAPSHOT.jar:na]
        at com.intel.mountwilson.trustagent.commands.hostinfo.HostInfoCmd.execute(HostInfoCmd.java:45) ~[mtwilson-trustagent-ws-v2-2.2-SNAPSHOT.jar:na]
        ... 68 common frames omitted
2017-08-18 17:50:28,891 DEBUG [qtp1666392491-86] c.i.mtwilson.util.ThrowableMapper - ThrowableMapper locale: English (United States)
2017-08-18 17:50:28,891 DEBUG [qtp1666392491-86] c.i.mtwilson.util.ThrowableMapper - ThrowableMapper exception is NOT a subclass of MWException
2017-08-18 17:50:28,891 DEBUG [qtp1666392491-86] c.i.mtwilson.util.ThrowableMapper - Message toString with locale: en_US
2017-08-18 17:50:28,891 DEBUG [qtp1666392491-86] c.i.mtwilson.util.ThrowableMapper - Message toString loaded resource bundle:
2017-08-18 17:50:28,891 ERROR [qtp1666392491-86] c.i.mtwilson.util.ThrowableMapper - No translation for key com.intel.mountwilson.common.TAException in bundle java.util.PropertyResourceBundle: Can't find resource for bundle java.util.PropertyResourceBundle, key com.intel.mountwilson.common.TAException
2017-08-18 17:50:28,891 DEBUG [qtp1666392491-86] c.i.mtwilson.util.ThrowableMapper - ThrowableMapper getLocalizedErrorMessage return ok
2017-08-18 17:50:28,891 DEBUG [qtp1666392491-86] c.i.mtwilson.util.ThrowableMapper - ThrowableMapper localizedMessage: com.intel.mountwilson.common.TAException
2017-08-18 17:50:28,891 DEBUG [qtp1666392491-86] c.i.mtwilson.util.ThrowableMapper - ThrowableMapper exception is NOT a subclass of WebApplicationException
2017-08-18 17:50:28,891 DEBUG [qtp1666392491-86] c.i.m.j.s.filter.ErrorLogFilter - Incident Tag #6ca30f7a_

**Comment by JordunoInt** [comment]
Hey, did you know if you installed the KVM before or after the trust agent? because maybe you dont have KVM installed, please run this: **virsh -version** on the host (where you have the trust agent installed)

Please let me know the results.

**Comment by ZahediAquino** [comment]
Please provide the contents of /opt/trustagent/var/system-info/virsh.version also.

**Comment by ZahediAquino** [comment]
If the virsh.version file is empty, try running tagent update-system-info and check the contents of the file again.
