### ISSUE TITLE
NullPointerException. [MS_HOST_COMMUNICATION_ERROR] 

### ISSUE THREAD

**Issue by jemm14** [opencit/opencit#7]
This happens when I try to **import a white list for trusted host**  

catalina.out:

[catalina.out.zip](https://github.com/opencit/opencit/files/333564/catalina.out.zip)

this is the request and response : 

`2016-06-26 14:33:28,350 INFO [http-bio-8443-exec-10] c.i.d.c.j.PersistenceManager [PersistenceManager.java:77] PersistenceManager is configured with 3 factories in getEntityManagerFactory
Jun 26, 2016 2:33:28 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * LoggingFilter - Request received on thread http-bio-8443-exec-10
1 > GET https://192.168.122.118:1443/v2/host
1 > Accept: application/json
1 > Authorization: Basic bXR3aWxzb246
Jun 26, 2016 2:33:29 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 2 * LoggingFilter - Response received on thread http-bio-8443-exec-10
2 < 200
2 < Content-Length: 247
2 < Expires: Thu, 01 Jan 1970 00:00:00 GMT
2 < Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sat, 25-Jun-2016 12:33:28 GMT,JSESSIONID=16z6lo8tmbie1onqjwelkukmz;Path=/;Secure
2 < Content-Type: application/json
2 < Server: Jetty(9.1.0.RC2)
{"timestamp":1466944409211,"error_code":"OK","error_message":"OK","os_name":"Ubuntu","os_version":"14.04","bios_oem":"Bochs","bios_version":"Bochs","processor_info":" 63 06 00 00 FD FB 8B
 07","hardware_uuid":"D22A917A-5514-D18F-D872-77BFA4903AAD"}
`

and this is the concerning part of the log (catalina.out):

`
2016-06-26 14:33:29,203 ERROR [http-bio-8443-exec-10] c.i.m.m.b.HostBO [HostBO.java:730] Unexpected error in configureWhiteListFromCustomData: null
2016-06-26 14:33:29,208 ERROR [http-bio-8443-exec-10] c.i.m.m.b.HostBO [HostBO.java:914] Error during white list configuration. MS_HOST_COMMUNICATION_ERROR :Error during communication wit
h the host. Please verify the host parameters. NullPointerException.
2016-06-26 14:33:29,212 INFO [http-bio-8443-exec-10] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be
 obtained.
2016-06-26 14:33:29,212 INFO [http-bio-8443-exec-10] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be
 obtained.
2016-06-26 14:33:29,212 INFO [http-bio-8443-exec-10] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be
 obtained.
2016-06-26 14:33:29,215 ERROR [http-bio-8443-exec-2] c.i.m.S.ManagementConsoleServicesImpl [ManagementConsoleServicesImpl.java:124] Failed to configure whitelist: Error during communicati
on with the host. Please verify the host parameters. NullPointerException. [MS_HOST_COMMUNICATION_ERROR] 
com.intel.mtwilson.api.ApiException: Error during communication with the host. Please verify the host parameters. NullPointerException. [MS_HOST_COMMUNICATION_ERROR] 
        at com.intel.mtwilson.ApiClient.error(ApiClient.java:471)
        at com.intel.mtwilson.ApiClient.content(ApiClient.java:511)
        at com.intel.mtwilson.ApiClient.text(ApiClient.java:528)
        at com.intel.mtwilson.ApiClient.configureWhiteList(ApiClient.java:1530)
        at com.intel.mountwilson.Service.ManagementConsoleServicesImpl.saveWhiteListConfiguration(ManagementConsoleServicesImpl.java:121)
        at com.intel.mountwilson.controller.ManagementConsoleDataController.uploadWhiteListConfiguration(ManagementConsoleDataController.java:286)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.servlet.mvc.multiaction.MultiActionController.invokeNamedMethod(MultiActionController.java:471)
        at org.springframework.web.servlet.mvc.multiaction.MultiActionController.handleRequestInternal(MultiActionController.java:408)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at com.intel.mountwilson.security.SecurityFilter.doFilter(SecurityFilter.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
`

what did I miss?

Greetings.

**Comment by mgarciacervigon** [comment]
Hi!
Did you find a solution?
Manu

**Comment by adolfovega** [comment]
Hi,

Are you using a firewall? In your trusted host try to open port 1443 and see if that works. 
In Ubuntu it might be something like:

ufw allow 1443

Also, please check in your trusted host if the trustagent is up and running:

tagent status

Then stop/restart trustagent:

tagent stop
tagent start
