### ISSUE TITLE
[SOLVED] Import whitelist from trusted host [MS_HOST_COMMUNICATION_ERROR]

### ISSUE THREAD

**Issue by sloddo** [opencit/opencit#71]
I have installed OpenCIT 3.2 on machines with Ubuntu 16.04.2 LTS and TPM 1.2.
When I try to import whitelist I get a communication error on the server side.
On the host side, the trustagent.log shows the absence of aikquote file.

This is a part of the server log (catalina.out)
`2017-10-31 16:31:43,037 ERROR [http-bio-8443-exec-8] c.i.m.m.b.HostBO [HostBO.java:996] Error during white list configuration. MS_HOST_COMMUNICATION_ERROR :Error during communication with the host. Please verify the host parameters. IOException.
2017-10-31 16:31:43,039 INFO [http-bio-8443-exec-8] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-10-31 16:31:43,040 INFO [http-bio-8443-exec-8] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-10-31 16:31:43,040 INFO [http-bio-8443-exec-8] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
2017-10-31 16:31:43,041 ERROR [http-bio-8443-exec-2] c.i.m.S.ManagementConsoleServicesImpl [ManagementConsoleServicesImpl.java:126] Failed to configure whitelist: Error during communication with the host. Please verify the host parameters. IOException. [MS_HOST_COMMUNICATION_ERROR] 
com.intel.mtwilson.api.ApiException: Error during communication with the host. Please verify the host parameters. IOException. [MS_HOST_COMMUNICATION_ERROR] 
	at com.intel.mtwilson.ApiClient.error(ApiClient.java:475)
	at com.intel.mtwilson.ApiClient.content(ApiClient.java:515)
	at com.intel.mtwilson.ApiClient.text(ApiClient.java:532)
	at com.intel.mtwilson.ApiClient.configureWhiteList(ApiClient.java:1534)
	at com.intel.mountwilson.Service.ManagementConsoleServicesImpl.saveWhiteListConfiguration(ManagementConsoleServicesImpl.java:123)
	at com.intel.mountwilson.controller.ManagementConsoleDataController.uploadWhiteListConfiguration(ManagementConsoleDataController.java:312)
	at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.servlet.mvc.multiaction.MultiActionController.invokeNamedMethod(MultiActionController.java:471)
	at org.springframework.web.servlet.mvc.multiaction.MultiActionController.handleRequestInternal(MultiActionController.java:408)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.intel.mountwilson.security.SecurityFilter.doFilter(SecurityFilter.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

This is a part of the host log (trustagent.log)
`2017-10-31 16:31:47,275 DEBUG [qtp1512903453-24] c.intel.mtwilson.util.exec.ExecUtil - Executing command: /opt/trustagent/share/tpmquote/bin/aikquote with arguments: [-p, f0d6d977c18ba2e61a8ff50becfc7dcce64415bb, -c, /opt/trustagent/repository/3e6928a2/nonce, /opt/trustagent/configuration/aik.blob, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, /opt/trustagent/repository/3e6928a2/aikquote]
2017-10-31 16:31:47,282 DEBUG [qtp1512903453-24] c.i.mtwilson.util.ThrowableMapper - ThrowableMapper toResponse
com.intel.mountwilson.common.TAException: Error while generating quote
	at com.intel.mountwilson.trustagent.commands.GenerateQuoteCmd.execute(GenerateQuoteCmd.java:261) ~[mtwilson-trustagent-ws-v2-3.2-SNAPSHOT.jar:na]
	at com.intel.mtwilson.trustagent.ws.v2.Tpm.tpmQuote(Tpm.java:150) ~[mtwilson-trustagent-ws-v2-3.2-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.4.1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151) ~[jersey-server-2.4.1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171) ~[jersey-server-2.4.1.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195) ~[jersey-server-2.4.1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104) ~[jersey-server-2.4.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:367) ~[jersey-server-2.4.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349) ~[jersey-server-2.4.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106) ~[jersey-server-2.4.1.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259) ~[jersey-server-2.4.1.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.4.1.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.4.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.4.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.4.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.4.1.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318) [jersey-common-2.4.1.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236) [jersey-server-2.4.1.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:983) [jersey-server-2.4.1.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:361) [jersey-container-servlet-core-2.4.1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:372) [jersey-container-servlet-core-2.4.1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335) [jersey-container-servlet-core-2.4.1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:218) [jersey-container-servlet-core-2.4.1.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1568) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.2.2.jar:1.2.2]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.2.2.jar:1.2.2]
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) [shiro-core-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.2.2.jar:1.2.2]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.2.jar:1.2.2]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1556) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
	at com.intel.mtwilson.servlet.RepeatableRequestFilter.doFilter(RepeatableRequestFilter.java:46) [mtwilson-http-servlets-3.2-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1548) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:524) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568) [jetty-security-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1110) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:453) [jetty-servlet-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1044) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.Server.handle(Server.java:459) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229) [jetty-server-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505) [jetty-io-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:594) [jetty-util-9.1.0.RC2.jar:9.1.0.RC2]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:525) [jetty-util-9.1.0.RC2.jar:9.1.0.RC2]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.io.IOException: Cannot run program "/opt/trustagent/share/tpmquote/bin/aikquote" (in directory "."): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_131]
	at java.lang.Runtime.exec(Runtime.java:620) ~[na:1.8.0_131]
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58) ~[commons-exec-1.2.jar:1.2]
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:277) ~[commons-exec-1.2.jar:1.2]
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:334) ~[commons-exec-1.2.jar:1.2]
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:164) ~[commons-exec-1.2.jar:1.2]
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:151) ~[commons-exec-1.2.jar:1.2]
	at com.intel.mtwilson.util.exec.ExecUtil.execute(ExecUtil.java:59) ~[mtwilson-util-exec-3.2-SNAPSHOT.jar:na]
	at com.intel.mountwilson.trustagent.commands.GenerateQuoteCmd.execute(GenerateQuoteCmd.java:250) ~[mtwilson-trustagent-ws-v2-3.2-SNAPSHOT.jar:na]
	... 68 common frames omitted
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method) ~[na:1.8.0_131]
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247) ~[na:1.8.0_131]
	at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[na:1.8.0_131]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[na:1.8.0_131]
	... 76 common frames omitted
2017-10-31 16:31:47,282 DEBUG [qtp1512903453-24] c.i.mtwilson.util.ThrowableMapper - ThrowableMapper locale: English (United States)
2017-10-31 16:31:47,282 DEBUG [qtp1512903453-24] c.i.mtwilson.util.ThrowableMapper - ThrowableMapper exception is NOT a subclass of MWException
2017-10-31 16:31:47,282 DEBUG [qtp1512903453-24] c.i.mtwilson.util.ThrowableMapper - Message toString with locale: en_US
2017-10-31 16:31:47,282 DEBUG [qtp1512903453-24] c.i.mtwilson.util.ThrowableMapper - Message toString loaded resource bundle: 
2017-10-31 16:31:47,283 ERROR [qtp1512903453-24] c.i.mtwilson.util.ThrowableMapper - No translation for key com.intel.mountwilson.common.TAException in bundle java.util.PropertyResourceBundle: Can't find resource for bundle java.util.PropertyResourceBundle, key com.intel.mountwilson.common.TAException
2017-10-31 16:31:47,283 DEBUG [qtp1512903453-24] c.i.mtwilson.util.ThrowableMapper - ThrowableMapper getLocalizedErrorMessage return ok
2017-10-31 16:31:47,283 DEBUG [qtp1512903453-24] c.i.mtwilson.util.ThrowableMapper - ThrowableMapper localizedMessage: com.intel.mountwilson.common.TAException
2017-10-31 16:31:47,283 DEBUG [qtp1512903453-24] c.i.mtwilson.util.ThrowableMapper - ThrowableMapper exception is NOT a subclass of WebApplicationException
2017-10-31 16:31:47,283 DEBUG [qtp1512903453-24] c.i.d.c.i.LocalizableResponseFilter - LocalizationResponseFilter
2017-10-31 16:31:47,283 DEBUG [qtp1512903453-24] c.i.d.c.i.LocalizableResponseFilter - Client acceptable languages: [*]
2017-10-31 16:31:47,283 DEBUG [qtp1512903453-24] c.i.d.c.i.LocalizableResponseFilter - Response entity is null? not null
2017-10-31 16:31:47,283 DEBUG [qtp1512903453-24] c.i.d.c.i.LocalizableResponseFilter - Response entity class: java.lang.String
2017-10-31 16:31:47,283 DEBUG [qtp1512903453-24] c.i.d.c.i.LocalizableResponseFilter - Response entity localizable? false
2017-10-31 16:31:47,283 DEBUG [qtp1512903453-24] c.i.m.j.s.filter.ErrorLogFilter - Incident Tag #54c3f7c0
2017-10-31 16:31:47,283 DEBUG [qtp1512903453-24] c.i.d.c.i.LocalizableResponseFilter - LocalizationResponseFilter
2017-10-31 16:31:47,283 DEBUG [qtp1512903453-24] c.i.d.c.i.LocalizableResponseFilter - Client acceptable languages: [*]
2017-10-31 16:31:47,283 DEBUG [qtp1512903453-24] c.i.d.c.i.LocalizableResponseFilter - Response entity is null? not null
2017-10-31 16:31:47,284 DEBUG [qtp1512903453-24] c.i.d.c.i.LocalizableResponseFilter - Response entity class: java.lang.String
2017-10-31 16:31:47,284 DEBUG [qtp1512903453-24] c.i.d.c.i.LocalizableResponseFilter - Response entity localizable? false
`

Do you have any hints on how to solve this problem?

Thanks

**Comment by sloddo** [comment]
I have found the missing file (aikquote) in the build machine under the directory opencit-contrib/features/tpm-agent-tools/target/, I copy that file and paste it in the trust agent under /opt/trustagent/share/tpmquote/bin/. Now the problem is solved.
