### ISSUE TITLE
MS_HOST_COMMUNICATION_ERROR

### ISSUE THREAD

**Issue by jemm14** [opencit/opencit#8]
I really cannot get what the problem is?

[catalina.out.zip](https://github.com/opencit/opencit/files/335360/catalina.out.zip)

`
2016-06-26 14:33:29,203 ERROR [http-bio-8443-exec-10] c.i.m.m.b.HostBO [HostBO.java:730] Unexpected error in configureWhiteListFromCustomData: null 2016-06-26 14:33:29,208 ERROR [http-bio-8443-exec-10] c.i.m.m.b.HostBO [HostBO.java:914] Error during white list configuration. MS_HOST_COMMUNICATION_ERROR :Error during communication wit h the host. Please verify the host parameters. NullPointerException. 2016-06-26 14:33:29,212 INFO [http-bio-8443-exec-10] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set. Authorization cache cannot be obtained. 2016-06-26 14:33:29,212 INFO [http-bio-8443-exec-10] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set. Authorization cache cannot be obtained. 2016-06-26 14:33:29,212 INFO [http-bio-8443-exec-10] o.a.s.r.AuthorizingRealm [AuthorizingRealm.java:248] No cache or cacheManager properties have been set. Authorization cache cannot be obtained. 2016-06-26 14:33:29,215 ERROR [http-bio-8443-exec-2] c.i.m.S.ManagementConsoleServicesImpl [ManagementConsoleServicesImpl.java:124] Failed to configure whitelist: Error during communicati on with the host. Please verify the host parameters. NullPointerException. [MS_HOST_COMMUNICATION_ERROR] com.intel.mtwilson.api.ApiException: Error during communication with the host. Please verify the host parameters. NullPointerException. [MS_HOST_COMMUNICATION_ERROR] at com.intel.mtwilson.ApiClient.error(ApiClient.java:471) at com.intel.mtwilson.ApiClient.content(ApiClient.java:511) at com.intel.mtwilson.ApiClient.text(ApiClient.java:528) at com.intel.mtwilson.ApiClient.configureWhiteList(ApiClient.java:1530) at com.intel.mountwilson.Service.ManagementConsoleServicesImpl.saveWhiteListConfiguration(ManagementConsoleServicesImpl.java:121) at com.intel.mountwilson.controller.ManagementConsoleDataController.uploadWhiteListConfiguration(ManagementConsoleDataController.java:286) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.springframework.web.servlet.mvc.multiaction.MultiActionController.invokeNamedMethod(MultiActionController.java:471) at org.springframework.web.servlet.mvc.multiaction.MultiActionController.handleRequestInternal(MultiActionController.java:408) 
`

I would really appreciate any help

Greetigs.

**Comment by ZahediAquino** [comment]
Hey... Let's try a couple of things...

Make sure ports on host are open (1443).
Try to restart the trust agent:
- tagent stop
- tagent start
  Send us the trustagent.log and http.log please, this is on the host side.

**Comment by jemm14** [comment]
here the logs:

[logs.zip](https://github.com/opencit/opencit/files/335503/logs.zip)

port 1443 is open , thereis communication between server and trust agent, in the catalina.out of the server there is even a request and response (200) from https://myhost:1443/v2/host. If I use that url in a browser I get:

`<host_info><timestamp>1467023981764</timestamp><errorCode>OK</errorCode><errorMessage>OK</errorMessage><osName>Ubuntu</osName><osVersion>14.04</osVersion><biosOem>Bochs</biosOem><biosVersion>Bochs</biosVersion><processorInfo> 63 06 00 00 FD FB 8B 07</processorInfo><hardwareUuid>D22A917A-5514-D18F-D872-77BFA4903AAD</hardwareUuid></host_info>`

if I use https://myhost:1443/v2/  in a browser I get an Internal server error 500

**Comment by yankunsam** [comment]
Did you resolve it?

**Comment by ryansavino** [comment]
Looks like there was an error during installation:
`6111 [main] ERROR c.i.m.s.console.cmd.SetupManager - Error from RequestEndorsementCertificate: Validation failed
6111 [main] WARN  c.i.m.s.console.cmd.SetupManager - Validating RequestEndorsementCertificate: Unable to verify TPM EC with 15 authorities from /opt/trustagent/configuration/endorsement.pem.EC is also not registered with Mt.Wilson
6116 [main] ERROR com.intel.dcsg.cpg.console.Main - Error while executing setup: Encountered errors during setup`

You should be able to reproduce the error using this command:
`tagent request-endorsement-certificate`

DEBUG logging will provide more information. Can you provide both trustagent and attestation service logs in DEBUG mode when you run this command?
